name: 构建和发布

on:
  push:
    tags:
      - 'v*' # 当推送标签如 v1.0.0 时触发

jobs:
  build-and-release-android:
    name: 构建并发布Android版本
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Java环境
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: 设置Flutter环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: 缓存Pub依赖
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            .dart_tool/
            build/
          key: ${{ runner.os }}-pub-android-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-android-
      
      - name: 获取依赖
        run: flutter pub get
      
      - name: 构建ARM64 APK
        run: flutter build apk --release --target-platform android-arm64
      
      - name: 创建Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          name: 喵币 ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ios:
    name: 构建iOS版本
    runs-on: macos-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Flutter环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: 缓存Pub依赖
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            .dart_tool/
            ios/Pods/
            build/
          key: ${{ runner.os }}-pub-ios-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-ios-
      
      - name: 获取依赖
        run: flutter pub get
      
      - name: 构建iOS应用
        run: |
          flutter build ios --release --no-codesign
          cd ios
          mkdir -p build/archive
      
      # 注意：由于iOS应用需要签名和证书，这里只构建但不打包为IPA
      # 如需完整的iOS发布流程，需要添加证书、配置文件和签名步骤
      - name: 上传iOS构建结果
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: ios/build/
          retention-days: 5 